[versions]
kotlin = "2.3.21"
agp = "8.13.2"
compose-multiplatform = "1.10.1"
android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "26"
androidx-activityCompose = "1.11.0"
compose-materialIcons = "1.7.3"

[libraries]
compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "compose-materialIcons" }
kotlin-test ={ module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
