import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { argbFromHex, Hct, MaterialDynamicColors, SchemeTonalSpot } from '@material/material-color-utilities';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const seed = readFileSync(join(root, 'design/seed'), 'utf8').trim();
if (!/^[0-9a-f]{64}$/.test(seed)) {
  throw new Error('design/seed must be exactly 64 lowercase hex characters');
}

const seedColor = `#${seed.slice(0, 6)}`;

// Order matters: the seed indexes into these lists, so reordering changes the design.
const headingFonts = [
  'Lora', 'Merriweather', 'Playfair Display', 'Source Serif 4',
  'Crimson Pro', 'Fraunces', 'EB Garamond', 'Newsreader',
];
const bodyFonts = [
  'Inter', 'Source Sans 3', 'Nunito Sans', 'Work Sans',
  'IBM Plex Sans', 'DM Sans', 'Figtree', 'Manrope',
];
const headingFont = headingFonts[parseInt(seed.slice(6, 8), 16) % headingFonts.length];
const bodyFont = bodyFonts[parseInt(seed.slice(8, 10), 16) % bodyFonts.length];

const colorRoles = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceTint', 'inverseSurface', 'inverseOnSurface',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'outline', 'outlineVariant', 'scrim',
  'surfaceBright', 'surfaceDim', 'surfaceContainerLowest', 'surfaceContainerLow',
  'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest',
];

function colorSchemeArgs(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seedColor)), isDark, 0);
  return colorRoles
    .map((role) => {
      const argb = (MaterialDynamicColors[role].getArgb(scheme) >>> 0).toString(16).toUpperCase().padStart(8, '0');
      return `    ${role} = Color(0x${argb}),`;
    })
    .join('\n');
}

const colorKt = `// Generated by design/generate-theme.mjs from design/seed. Do not edit by hand.
package com.theseuntaylor.bookawards.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightColorScheme = lightColorScheme(
${colorSchemeArgs(false)}
)

val DarkColorScheme = darkColorScheme(
${colorSchemeArgs(true)}
)
`;

writeFileSync(join(root, 'composeApp/src/commonMain/kotlin/com/theseuntaylor/bookawards/theme/Color.kt'), colorKt);
console.log(`Seed color ${seedColor} -> Color.kt`);

// M3's type scale only uses regular (400) and medium (500).
const fontWeights = { regular: 400, medium: 500 };
const fontDir = join(root, 'composeApp/src/commonMain/composeResources/font');
const licenseDir = join(root, 'composeApp/src/commonMain/composeResources/files/font-licenses');
mkdirSync(fontDir, { recursive: true });
mkdirSync(licenseDir, { recursive: true });

async function downloadFont(family, role) {
  const weights = Object.values(fontWeights).join(';');
  const cssUrl = `https://fonts.googleapis.com/css2?family=${family.replaceAll(' ', '+')}:wght@${weights}`;
  // A non-browser user agent makes Google Fonts serve static TTF files.
  const css = await (await fetch(cssUrl, { headers: { 'User-Agent': 'book-awards-generator' } })).text();
  for (const [name, weight] of Object.entries(fontWeights)) {
    const block = css.split('@font-face').find((b) => b.includes(`font-weight: ${weight};`));
    const url = block?.match(/url\((https:[^)]+\.ttf)\)/)?.[1];
    if (!url) throw new Error(`No ${weight} TTF for ${family}`);
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    writeFileSync(join(fontDir, `${role}_${name}.ttf`), bytes);
  }
  // The SIL Open Font License requires its text to ship with the font files.
  const licenseUrl = `https://raw.githubusercontent.com/google/fonts/main/ofl/${family.replaceAll(' ', '').toLowerCase()}/OFL.txt`;
  const license = await fetch(licenseUrl);
  if (!license.ok) throw new Error(`No OFL license found for ${family}`);
  writeFileSync(join(licenseDir, `${role}-OFL.txt`), await license.text());
  console.log(`${role} font: ${family}`);
}

await downloadFont(headingFont, 'heading');
await downloadFont(bodyFont, 'body');
