import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { argbFromHex, Hct, MaterialDynamicColors, SchemeTonalSpot } from '@material/material-color-utilities';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const seed = readFileSync(join(root, 'design/seed'), 'utf8').trim();
if (!/^[0-9a-f]{64}$/.test(seed)) {
  throw new Error('design/seed must be exactly 64 lowercase hex characters');
}

const seedColor = `#${seed.slice(0, 6)}`;

const colorRoles = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceTint', 'inverseSurface', 'inverseOnSurface',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'outline', 'outlineVariant', 'scrim',
  'surfaceBright', 'surfaceDim', 'surfaceContainerLowest', 'surfaceContainerLow',
  'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest',
];

function colorSchemeArgs(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seedColor)), isDark, 0);
  return colorRoles
    .map((role) => {
      const argb = (MaterialDynamicColors[role].getArgb(scheme) >>> 0).toString(16).toUpperCase().padStart(8, '0');
      return `    ${role} = Color(0x${argb}),`;
    })
    .join('\n');
}

const colorKt = `// Generated by design/generate-theme.mjs from design/seed. Do not edit by hand.
package com.theseuntaylor.bookawards.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightColorScheme = lightColorScheme(
${colorSchemeArgs(false)}
)

val DarkColorScheme = darkColorScheme(
${colorSchemeArgs(true)}
)
`;

writeFileSync(join(root, 'composeApp/src/commonMain/kotlin/com/theseuntaylor/bookawards/theme/Color.kt'), colorKt);
console.log(`Seed color ${seedColor} -> Color.kt`);
