import SwiftUI

// Mirrors the design seed's colours in composeApp/.../theme/Color.kt (generated by design/generate-theme.mjs);
// update these if the seed changes.
extension Color {
    static let brand = dynamic(light: 0x436833, dark: 0xA8D292)
    static let brandContainer = dynamic(light: 0xC4EFAC, dark: 0x2C4F1D)
    static let onBrandContainer = dynamic(light: 0x2C4F1D, dark: 0xC4EFAC)
    static let secondaryContainer = dynamic(light: 0xD8E7CB, dark: 0x3D4B36)
    static let onSecondaryContainer = dynamic(light: 0x3D4B36, dark: 0xD8E7CB)

    private static func dynamic(light: UInt32, dark: UInt32) -> Color {
        Color(UIColor { traits in rgb(traits.userInterfaceStyle == .dark ? dark : light) })
    }

    private static func rgb(_ hex: UInt32) -> UIColor {
        UIColor(
            red: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
}
